login:
    pattern:   /login
    defaults:  { _controller: TFTennisFilterBundle:Security:login }
    
login_check:
    pattern:   /login_check

tf_tennis_filter:
    resource: "@TFTennisFilterBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
